#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_sscs = env_modules.Clone()

glsl_header = env_sscs.GLSL_HEADER("contact_shadows.glsl")
env_sscs.Depends(glsl_header, ["#glsl_builders.py"])

sources = env_sscs.add_source_files(env.modules_sources, "*.cpp")
env_sscs.Depends(sources, glsl_header)
